In [1]:
import numpy as np 

NUMPY İLE ARRY

In [8]:
liste=np.array([1,2,3,4,5])
type(liste)

numpy.ndarray

In [12]:
listem= np.array([3.14 , 4.8 , 6] ,dtype=int)
listem

array([3, 4, 6])

SIFIRDAN ARRAY OLUŞTURMA

In [13]:
a=np.zeros(10,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
a=np.ones([3,5], dtype=float)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

SADECE BELİRLİ BİR SAYIDAN ARRAY OLUŞTURMA


In [18]:
a=np.full([3,5],3)
a

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [23]:
#İKİ DEĞER ARASINDA BELİRLİ ARTIŞLARLA DEĞERLERİ OLUŞTURUR.

a=np.arange(0,31,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [25]:
#İKİ DEĞER ARASINDA SEÇİLEN DEĞER KADAR SAYI OLUŞTURUR
a=np.linspace(0,2,10)
a


array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [27]:
#ortalaması 10 standart sapması 4 olan 3e 4 lük matris yazalım
np.random.normal(10,4,(3,4))

array([[12.20380996,  9.96056002, -1.32252779, 12.33007728],
       [10.27736412,  9.12325635, 10.97261669,  5.53600797],
       [12.39578516, 13.931789  , 11.40100268,  8.50908331]])

In [28]:
#integer değerlerle oluşturmak istersek
np.random.randint(1,12,(3,4))

array([[ 6,  4, 11,  5],
       [11,  3,  1, 10],
       [ 2,  1,  4,  9]])

ndim: boyut sırası
shape:boyut bilgisi
size: toplam eleman sayısı
dtype :  array veri tipi

In [13]:

x= np.random.randint(10 , size=10)
x.ndim
x


array([4, 3, 9, 3, 5, 4, 2, 2, 8, 0])

In [9]:
x.shape

(10,)

In [11]:
x.size

10

In [12]:
x.dtype

dtype('int32')

İKİ BOYUTLU ARRAY

In [16]:
b=np.random.randint(10, size=(3,5))
b

array([[6, 8, 9, 9, 5],
       [4, 3, 6, 3, 4],
       [1, 8, 0, 2, 1]])

In [17]:
b.ndim

2

In [18]:
b.shape

(3, 5)

In [19]:
b.size

15

In [20]:
b.dtype

dtype('int32')

VAR OLAN ARRAYİ ŞEKİLLENDİRME(RESHAPING)

In [21]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#var olan arraydan 3-3lük array yapma
a=np.arange(1,10).reshape(3,3)

In [28]:
a.ndim
a.dtype
type(a)

numpy.ndarray

ARRAY BİRLEŞTİRME(CONCATENATION)

In [29]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [31]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [32]:
z=np.array([7,8,9])

In [33]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#iki boyutlu array birleştirtme
a=np.array([[1,2,3],[4,5,6]])

In [37]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
#axsis 0 olursa satır bazlı 1 olursa sütun abzlı sıralama yapar.
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

ARRAY AYIRMA (SPLITING)

In [42]:
x=np.array([1,2,3,44,55,66,6,5,4])

In [44]:
np.split(x,[3,6])

[array([1, 2, 3]), array([44, 55, 66]), array([6, 5, 4])]

In [46]:
a,b,c=np.split(x,[3,6])
print(a)
print(b)
print(c)

[1 2 3]
[44 55 66]
[6 5 4]


In [48]:
#iki boyutlu ayırma
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [51]:
ust, alt=np.vsplit(m,[2])
print(ust)
print(alt)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [52]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [53]:
sag, sol=np.vsplit(m,[2])
print(sag)
print(sol)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


ARRAY SIRALAMA8 (SORTING)

In [63]:
v=np.array([2,3,4,6,8,5,1])
print(v)
print(sorted(v))
print(v.sort())
print(v)

[2 3 4 6 8 5 1]
[1, 2, 3, 4, 5, 6, 8]
None
[1 2 3 4 5 6 8]


In [66]:
#iki boyutlu arraylar için sıralama
m=np.random.normal(20,5,(3,3))
m

array([[20.99479718, 18.93942212, 14.48317829],
       [ 9.94491604, 15.50424061, 21.1250779 ],
       [11.17578572, 10.37533693, 17.86757033]])

In [68]:
#iki boyutlu arrayin satırlarını sıralamak için 
np.sort(m , axis=1)

array([[14.48317829, 18.93942212, 20.99479718],
       [ 9.94491604, 15.50424061, 21.1250779 ],
       [10.37533693, 11.17578572, 17.86757033]])

In [69]:
#iki boyutlu arrayin sütubnlarını  sıralamak için 
np.sort(m , axis=0)

array([[ 9.94491604, 10.37533693, 14.48317829],
       [11.17578572, 15.50424061, 17.86757033],
       [20.99479718, 18.93942212, 21.1250779 ]])

İNDEX VE ELEMANLARA ERİŞİM YAPMAK

In [71]:
x=np.random.randint(10,size=10)
x

array([8, 5, 2, 7, 8, 0, 5, 5, 8, 6])

In [74]:
x[1]
x[1]=12
x[1]

12

In [79]:
x=np.random.randint(10,size=(2,5))
print(x)


[[3 7 1 9 7]
 [5 6 6 5 2]]


3

In [84]:
x[1,2]

6

In [86]:
x[1,2]=3.2
x

array([[3, 7, 1, 9, 7],
       [5, 6, 3, 5, 2]])

slicing ile elemanlara erişmek (array alt kümesine erişmek)

In [87]:
a=np.arange(20,30)
a


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [93]:
print(a[0:3])
print(a[:3])
print(a[3:])
print(a[1::3])
print(a[0::2])

[20 21 22]
[20 21 22]
[23 24 25 26 27 28 29]
[21 24 27]
[20 22 24 26 28]


In [3]:
m=np.random.randint(10,size=(5,5))
m

array([[8, 3, 6, 7, 6],
       [9, 3, 6, 2, 5],
       [2, 0, 0, 5, 8],
       [5, 4, 6, 8, 3],
       [5, 3, 3, 3, 6]])

In [97]:
m[:,1]

array([3, 8, 6, 6, 5])

In [17]:
#iki boyutlu slice işlemleri
m=np.random.randint(10, size=(5,5))
m

array([[7, 2, 3, 5, 8],
       [0, 0, 4, 1, 1],
       [1, 5, 8, 9, 5],
       [0, 2, 6, 4, 2],
       [9, 5, 2, 2, 4]])

In [31]:
print(m[:,0])#ilk sütun
print()
print(m[:,1])#ikinci sütun
print()
print(m[0,:])#ilk satır
print()
print(m[0:2,0:3])#belirli alanda satırları ve sütunları alma 
print()
print(m[:,:2])#tüm satırların ilk 2 sütunlarını getrir
print()
print(m[1:3,0:2])




[7 0 1 0 9]

[2 0 5 2 5]

[7 2 3 5 8]

[[7 2 3]
 [0 0 4]]

[[7 2]
 [0 0]
 [1 5]
 [0 2]
 [9 5]]

[[0 0]
 [1 5]]


ALT KÜMLERELE İŞLEM YAPMAK 

In [33]:
a= np.random.randint(10,size=(5,5))
a


array([[1, 8, 2, 6, 0],
       [0, 3, 0, 2, 0],
       [0, 9, 4, 3, 0],
       [4, 1, 8, 3, 6],
       [4, 0, 5, 7, 0]])

In [35]:
alt_a=a[0:3,0:2]
alt_a

array([[1, 8],
       [0, 3],
       [0, 9]])

In [37]:
alt_a[0,0]=999
alt_a[1,1]=888

In [38]:
alt_a

array([[999,   8],
       [  0, 888],
       [  0,   9]])

In [39]:
a

array([[999,   8,   2,   6,   0],
       [  0, 888,   0,   2,   0],
       [  0,   9,   4,   3,   0],
       [  4,   1,   8,   3,   6],
       [  4,   0,   5,   7,   0]])

In [41]:
b= np.random.randint(10,size=(5,5))
b


array([[0, 2, 6, 2, 1],
       [7, 0, 6, 3, 5],
       [3, 2, 2, 1, 2],
       [3, 4, 5, 8, 3],
       [2, 6, 3, 1, 1]])

In [44]:
#seçilen arrayi yapılacak işlenmden bağımsızlaştırır ana arrayda değişim olmaz
alt_b=m[0:3,0:2].copy()

FANCY INDEX İLE ELEMANLARA EİŞMEK


In [51]:
import numpy as np
v=np.arange (0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [54]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [57]:
#elimizde bulununan binlerce veri içierisinden birden fazla değer almak için;
al_getir=[1,3,5]
v[al_getir]

array([ 3,  9, 15])

In [59]:
#iki boyutta fancy
m=np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
satir=np.array([0,1])
sutun=np.array([1,2])
print(satir)
print(sutun)

[0 1]
[1 2]


In [62]:
m[satir,sutun]

array([1, 5])

In [64]:
#basit index ile fancy index
m[0,[1,2]]

array([1, 2])

In [66]:
#slice ile fancy
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

KOŞULLU ELEMAN İŞLEMLERİ

In [68]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [71]:
print(v>5)
print(v>3)
print(v<3)

[False False False False False]
[False False False  True  True]
[ True  True False False False]


In [76]:
#mantıksal operatörler ile 
print(v[v<3])
print(v[v<=3])
print(v[v==3])
print(v[v>3])
print(v[v>=3])
print(v[v!=3])
v[v<3]

[1 2]
[1 2 3]
[3]
[4 5]
[3 4 5]
[1 2 4 5]


array([1, 2])

MATEMATİKSEL İŞLEMLER

In [77]:
v=np.array([1,2,3,4,5])
v

In [78]:
v-1

array([0, 1, 2, 3, 4])

In [79]:
#ufunc

np.subtract(v,1)#çıkartma işlemi yap

array([0, 1, 2, 3, 4])

In [80]:
np.add(v,1)#toplama işlemi

array([2, 3, 4, 5, 6])

In [82]:
np.multiply(v,4)#çarpma işlemi yap

array([ 4,  8, 12, 16, 20])

In [83]:
np.divide(v,3)#bölme işlemi yap

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [84]:
np.power(v,3)# üs alma işlemi yapar.

array([  1,   8,  27,  64, 125], dtype=int32)

In [86]:
np.mod(v,2)#mod alır 2 ye kalanları gösterir

array([1, 0, 1, 0, 1], dtype=int32)

In [89]:
np.absolute(np.array([-3]))#mutlak edeğer alma işlemini yapar.

array([3])

In [91]:
np.sin(360)#sin hesaplama yapar

0.9589157234143065

In [93]:
np.cos(180)#cos hesaplama yapar.

-0.5984600690578581

In [94]:
v=np.array([1,2,3])

In [97]:
#log değerlerini hesaplamada kullanma
print(np.log(v))
print(np.log2(v))
print(np.log10(v))

[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]


                İSTATİKSEL HESAPLAMALAR

In [103]:
print(v)
print(np.mean(v))#v nin ortalşamasını hesaplar
print(np.sum(v))#v nin toplam değerini hesaplar
print(np.min(v))#v nin min değerini bulur
print(np.max(v))#v nin max değerini hesaplar
print(np.var(v))#v nin varyansını  hesaplar
print(np.std(v))#v nin standart sapmasını  hesaplar
print(np.corrcoef(v))#v nin dönüş korelasyonunu  hesaplar


[1 2 3]
2.0
6
1
3
0.6666666666666666
0.816496580927726
1.0


            İKİ BİLİNMEYENLİ DENKLEM ÇÖZÜMÜ

5*x0+x1=12
x0+3*x1=10

In [105]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [106]:
print(a)
print(b)

[[5 1]
 [1 3]]
[12 10]


In [108]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [116]:
a=np.array([[4, 7, 4, 5, 9],
[2, 5, 0, 7, 7],
[1, 9, 0, 8, 2]])

a[:2, :3]

array([[4, 7, 4],
       [2, 5, 0]])

In [118]:
a=np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])
a[2,3]

8